version: '3.8'

services:
  backend:
    build: .  # Spring Boot backend in root directory
    container_name: spring-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/discord_clone?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: A@n12345
      SPRING_REDIS_HOST: host.docker.internal  # Use host's Redis service
      SPRING_REDIS_PORT: 6379  # Default Redis port
    ports:
      - "8082:8082"  # Map backend container port to host port 8082
    networks:
      - discord-clone-network

  frontend:
    build: ./frontend  # React app inside the frontend directory
    container_name: react-frontend
    ports:
      - "4173:80"  # Map frontend container port 80 to host port 3000
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8082  # Backend URL for the React app
    depends_on:
      - backend  # Ensure backend starts before frontend
    networks:
      - discord-clone-network

networks:
  discord-clone-network:
    driver: bridge
