# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/discord_clone

spring.datasource.username=anil
spring.datasource.password=an12345

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.com.discordclone.security=DEBUG
#logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG



#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# Server Configuration
server.port=8082


server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=a12345
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=mytls
server.ssl.key-password=a12345

#redis configuration
spring.redis.host=localhost
spring.redis.port=6379

# WebSocket Configuration
spring.websocket.max-text-message-size=8192
spring.websocket.max-binary-message-size=8192

# Logging Configuration
logging.level.org.springframework.web=INFO
logging.level.com.discordclone=DEBUG

# JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000
app.jwt.header=Authorization
app.jwt.prefix=Bearer 



# # Spring Security (Basic Authentication)
# spring.security.user.name=admin
# spring.security.user.password=$2a$10$hp6rMd9jdPqOODaA7zpgmO3xc9UiKL3K/I5no2pOJYFpEhLBjQ72G

# #{noop}adminpassword

logging.level.org.springframework.security.messaging=DEBUG

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.socket=DEBUG

logging.level=DEBUG
spring.mvc.static-path-pattern=/static/**


# Enable detailed WebSocket logs
logging.level.org.springframework.messaging.simp=DEBUG
logging.level.org.springframework.web.socket.sockjs=DEBUG

sonar.projectKey=discord-clone
sonar.organization=anilkr09
sonar.host.url=https://sonarcloud.io

sonar.token=07d85ed23560c71b29a01f13ee8a7b0c8694bdc7
sonar.login=07d85ed23560c71b29a01f13ee8a7b0c8694bdc7